import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  overwrite: true,
  schema: "http://localhost:4000/graphql",
  documents: "src/data/api/graphql/**/*.graphql",
  generates: {
    "src/data/types/generated.ts": {
      plugins: ["typescript"],
      config: {
        maybeValue: "T",
      },
    },
    "src/": {
      preset: "near-operation-file",
      presetConfig: {
        baseTypesPath: "data/types/generated.ts",
      },
      plugins: [
        {
          add: {
            content:
              "/* eslint-disable */ /** *\n * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!\n *\n * instead, edit one of the `.graphql` files in this project and run\n *\n * npm run graphql-codegen\n *\n * for this file to be re-created\n */\n",
          },
        },
        // {
        //   add: {
        //     content: "module.hot?.accept();",
        //   },
        // },
        "typescript-operations",
        {
          "typescript-rtk-query": {
            importBaseApiFrom: "src/data/api",
            exportHooks: true,
            // overrideExisting: 'module.hot?.status() === "apply"',
          },
        },
      ],
      config: {
        maybeValue: "T",
      },
    },
    "src/data/api/.introspection.json": {
      plugins: ["introspection"],
    },
  },
};
export default config;
