/* eslint-disable */ /** *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from '../../types/generated';

import { api } from 'src/data/api';
export type RdmSubscriptionSubscriptionVariables = Types.Exact<{ [key: string]: never; }>;


export type RdmSubscriptionSubscription = { __typename?: 'Subscription', randomNumber: number };


export const RdmSubscriptionDocument = `
    subscription RdmSubscription {
  randomNumber
}
    `;

const injectedRtkApi = api.injectEndpoints({
  endpoints: (build) => ({
  }),
});

export { injectedRtkApi as api };
export const {  } = injectedRtkApi;

